apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-api-ingress
spec:
  rules:
    - host: crud-api.example.com  # Replace with your actual domain name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crud-api-service
                port:
                  number: 80
