# templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-crud-api.fullname" . }}
  labels:
    app: {{ include "flask-crud-api.name" . }}
spec:
  rules:
    - host: your-domain.com
      http:
        paths:
          - path: /items
            pathType: Prefix
            backend:
              service:
                name: {{ include "flask-crud-api.fullname" . }}
                port:
                  number: 80
