# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-crud-api.fullname" . }}
  labels:
    app: {{ include "flask-crud-api.name" . }}
spec:
  selector:
    app: {{ include "flask-crud-api.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: {{ .Values.service.type }}
