name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-api-image .

      - name: Tag Docker image
        run: docker tag my-api-image terraformrg.azurecr.io/my-api-image:v7

      - name: Push Docker image to Azure Container Registry
        run: docker push terraformrg.azurecr.io/my-api-image:v7

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: 'Terraform Init'
        working-directory: "${{ github.workspace }}/aks-terraform"
        id: check_aks
        run: |
          terraform init
          terraform validate
          terraform plan
          AKS_EXIST=$(az aks list --resource-group api-demo --query "length([])" -o tsv)
          echo "AKS_EXIST=$AKS_EXIST" >> $GITHUB_ENV
          
      - name: Deploy AKS with Terraform
        working-directory: "${{ github.workspace }}/aks-terraform"
        if: env.AKS_EXIST == '0'
        run: |
          terraform apply --auto-approve

      - name: Azure AKS Set Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: my-aks-cluster
          resource-group: api-demo

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Deploy to AKS
        working-directory: "${{ github.workspace }}"
        run: |
          helm lint ./helm
          helm install my-crud-api-2 ./helm 